name: .NET

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production pages deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Bootstrap
      run: make bootstrap

    - name: Build
      run: make cibuild

    - name: Test
      run: make citest

  acceptance-test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Bootstrap
      run: make bootstrap

    - name: Build
      run: make cibuild

    - name: Run acceptance tests
      run: make citest-acceptance

    - name: Copy results
      if: always()
      run: cp -r LevelUpGame.Tests/resources ./test-results

    - name: Export pretty results
      if: always()
      run: export DOTNET_ROOT=$(which dotnet) & livingdoc test-assembly LevelUpGame.Tests/bin/Debug/net6.0/LevelUpGame.Tests.dll -t LevelUpGame.Tests/bin/Debug/net6.0/TestExecution.json -o test-results/TestOutput.html

    - name: Setup Pages
      uses: actions/configure-pages@v3
      if: always()
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v2
      if: always()
      with:
        path: ./test-results
    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v2
